from __future__ import annotations

import os
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import llm_hud.installer as installer_module
from llm_hud.installer import STAGING_PREFIX, install_runtime_from_source
from llm_hud.runtime import (
    INSTALL_MARKER_NAME,
    INSTALL_MARKER_VALUE,
    RuntimeLayoutError,
    activate,
    read_activation,
    runtime_path,
    validate_runtime,
)


ROOT = Path(__file__).resolve().parents[1]


def owned_root(path: Path) -> None:
    (path / INSTALL_MARKER_NAME).write_text(f"{INSTALL_MARKER_VALUE}\n")


def copy_runtime_checkout(destination: Path) -> None:
    for name in ("src", "bin"):
        shutil.copytree(ROOT / name, destination / name)
    for name in ("README.md", "LICENSE", "pyproject.toml"):
        shutil.copy2(ROOT / name, destination / name)


class RuntimeInstallerTests(unittest.TestCase):
    def test_installs_from_a_checkout_while_filtering_python_caches(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "runtime"
            root.mkdir()
            owned_root(root)

            metadata, activation = install_runtime_from_source(ROOT, root)

            self.assertEqual(activation.active, metadata.release_id)
            runtime = runtime_path(root, metadata.release_id)
            self.assertEqual(validate_runtime(root, metadata.release_id), metadata)
            self.assertFalse(any(runtime.rglob("__pycache__")))
            self.assertFalse(any(runtime.rglob("*.pyc")))
            self.assertFalse(any(root.glob(f"{STAGING_PREFIX}*")))

    def test_reinstall_is_idempotent_and_does_not_self_reference(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "runtime"
            root.mkdir()
            owned_root(root)
            first_metadata, first_activation = install_runtime_from_source(ROOT, root)
            activation_bytes = (root / "activation").read_bytes()

            second_metadata, second_activation = install_runtime_from_source(ROOT, root)

            self.assertEqual(second_metadata, first_metadata)
            self.assertEqual(second_activation, first_activation)
            self.assertIsNone(second_activation.previous)
            self.assertEqual((root / "activation").read_bytes(), activation_bytes)
            self.assertEqual(len(list((root / "versions").iterdir())), 1)

    def test_unsafe_source_leaves_existing_activation_unchanged(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            root = base / "runtime"
            source = base / "source"
            root.mkdir()
            source.mkdir()
            owned_root(root)
            install_runtime_from_source(ROOT, root)
            before = (root / "activation").read_bytes()
            copy_runtime_checkout(source)
            external = base / "external"
            external.write_text("outside")
            (source / "README.md").unlink()
            (source / "README.md").symlink_to(external)

            with self.assertRaisesRegex(RuntimeLayoutError, "symlink"):
                install_runtime_from_source(source, root)

            self.assertEqual((root / "activation").read_bytes(), before)
            self.assertEqual(external.read_text(), "outside")
            self.assertFalse(any(root.glob(f"{STAGING_PREFIX}*")))

    def test_bytecode_outside_cache_is_rejected_before_staging(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            root = base / "runtime"
            source = base / "source"
            root.mkdir()
            source.mkdir()
            owned_root(root)
            copy_runtime_checkout(source)
            (source / "src" / "unexpected.pyc").write_bytes(b"bytecode")

            with self.assertRaisesRegex(RuntimeLayoutError, "outside __pycache__"):
                install_runtime_from_source(source, root)

            self.assertFalse((root / "activation").exists())
            self.assertFalse((root / ".llm-hud-layout").exists())

    def test_cache_with_non_bytecode_content_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            root = base / "runtime"
            source = base / "source"
            root.mkdir()
            source.mkdir()
            owned_root(root)
            copy_runtime_checkout(source)
            cache = source / "src" / "llm_hud" / "__pycache__"
            cache.mkdir(exist_ok=True)
            (cache / "sentinel.txt").write_text("not generated bytecode")

            with self.assertRaisesRegex(RuntimeLayoutError, "unsafe non-bytecode"):
                install_runtime_from_source(source, root)

            self.assertIsNone(read_activation(root))

    def test_source_hard_link_is_rejected_without_touching_external_file(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            root = base / "runtime"
            source = base / "source"
            root.mkdir()
            source.mkdir()
            owned_root(root)
            copy_runtime_checkout(source)
            external = base / "external"
            external.write_text("outside")
            (source / "README.md").unlink()
            os.link(external, source / "README.md")

            with self.assertRaisesRegex(RuntimeLayoutError, "regular"):
                install_runtime_from_source(source, root)

            self.assertEqual(external.read_text(), "outside")
            self.assertFalse((root / "activation").exists())
            self.assertFalse((root / ".llm-hud-layout").exists())

    def test_cleanup_does_not_delete_a_replacement_staging_directory(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "runtime"
            root.mkdir()
            owned_root(root)

            def replace_staging(source: Path, staging: Path) -> None:
                del source
                staging.rename(staging.with_name(f"{staging.name}-original"))
                staging.mkdir()
                (staging / "sentinel").write_text("replacement")
                raise RuntimeLayoutError("simulated copy failure")

            with mock.patch(
                "llm_hud.installer.copy_runtime_source",
                side_effect=replace_staging,
            ):
                with self.assertRaisesRegex(RuntimeLayoutError, "simulated"):
                    install_runtime_from_source(ROOT, root)

            replacements = [
                path
                for path in root.glob(f"{STAGING_PREFIX}*")
                if (path / "sentinel").exists()
            ]
            self.assertEqual(len(replacements), 1)
            self.assertEqual((replacements[0] / "sentinel").read_text(), "replacement")

    def test_concurrent_activation_is_not_overwritten_after_copy(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            root = base / "runtime"
            changed_source = base / "changed-source"
            root.mkdir()
            changed_source.mkdir()
            owned_root(root)
            first_metadata, _ = install_runtime_from_source(ROOT, root)
            copy_runtime_checkout(changed_source)
            with (changed_source / "README.md").open("a") as handle:
                handle.write("\nchanged runtime\n")
            second_metadata, _ = install_runtime_from_source(changed_source, root)
            original_copy = installer_module.copy_runtime_source

            def activate_during_copy(source: Path, staging: Path) -> None:
                activate(root, first_metadata.release_id)
                original_copy(source, staging)

            with mock.patch(
                "llm_hud.installer.copy_runtime_source",
                side_effect=activate_during_copy,
            ):
                with self.assertRaisesRegex(RuntimeLayoutError, "active runtime changed"):
                    install_runtime_from_source(changed_source, root)

            current = read_activation(root)
            assert current is not None
            self.assertEqual(current.active, first_metadata.release_id)
            self.assertEqual(current.previous, second_metadata.release_id)


if __name__ == "__main__":
    unittest.main()
